[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = admin
db_host = aws-0-us-west-2.pooler.supabase.com
db_port = 6543
db_name = postgres
db_user = postgres.ucawlwunpdiebuutndlr
db_password = aGSOtjZmJpTQBfnt
http_port = 8069
proxy_mode = True
